name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install schemachange

      - name: Run schemachange
        run: |
          schemachange -f scripts/ \
            -a "SUNLIFE-US" \
            -u "charlie.mccarthy@sunlife.com" \
            -r "USER_SNO_MI_DEV" \
            -w "XS_SYS_INGES"T \
            -d "SUN360_SOURCE_DEV" \
            -s "PUBLIC" \
            -p DF72tiOrt87]wty2
        env:
          SNOWFLAKE_ACCOUNT: "SUNLIFE-US"
          SNOWFLAKE_USER: "charlie.mccarthy@sunlife.com"
          SNOWFLAKE_PASSWORD: DF72tiOrt87]wty2
